package main

import (
	"fmt"
	"os"
	"runtime/debug"
	"strings"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/achton/cc360/internal/config"
	"github.com/achton/cc360/internal/db"
	"github.com/achton/cc360/internal/demo"
	"github.com/achton/cc360/internal/scanner"
	"github.com/achton/cc360/internal/tui"
)

// version is set via -ldflags by GoReleaser. For `go install` builds it stays
// "dev", so buildVersion falls back to the module version from build info.
var version = "dev"

// buildVersion returns the release version, preferring the ldflags value and
// falling back to the module version embedded by `go install`.
func buildVersion() string {
	if version != "dev" {
		return version
	}
	if info, ok := debug.ReadBuildInfo(); ok {
		if v := info.Main.Version; v != "" && v != "(devel)" {
			return v
		}
	}
	return version
}

func main() {
	// Handle --version / -v flag
	if len(os.Args) == 2 && (os.Args[1] == "--version" || os.Args[1] == "-v") {
		fmt.Printf("cc360 %s\n", buildVersion())
		return
	}

	// Handle --demo flag
	if len(os.Args) == 2 && os.Args[1] == "--demo" {
		runDemo()
		return
	}

	// Recover terminal state on panic (raw mode, cursor, mouse mode)
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintf(os.Stderr, "cc360 panic: %v\n", r)
			os.Exit(1)
		}
	}()

	cfg, shouldExit, err := config.Load()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	if shouldExit {
		return
	}

	sessions, err := scanner.Scan(cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error scanning sessions: %v\n", err)
		os.Exit(1)
	}

	database, err := db.Open("")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error opening database: %v\n", err)
		os.Exit(1)
	}
	defer database.Close()

	if err := database.Upsert(sessions); err != nil {
		fmt.Fprintf(os.Stderr, "Error upserting sessions: %v\n", err)
		os.Exit(1)
	}

	// Prune sessions no longer found on disk
	scannedIDs := make([]string, len(sessions))
	for i, s := range sessions {
		scannedIDs[i] = s.SessionID
	}
	if _, err := database.PruneUnseen(scannedIDs, cfg.ScanPaths); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: could not prune stale sessions: %v\n", err)
	}

	all, err := database.AllSessions(cfg.SortBy, true)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error querying sessions: %v\n", err)
		os.Exit(1)
	}

	// Filter out non-interactive and non-resumable sessions
	filtered := make([]db.Session, 0, len(all))
	for _, s := range all {
		text := s.ExistingSummary + s.FirstPrompt
		if strings.Contains(text, "Caveat: The messages below were generated by the user while running") {
			continue
		}
		if strings.HasPrefix(s.FirstPrompt, "<teammate-message") {
			continue
		}
		// Skip sessions whose project path no longer exists
		if s.ProjectPath != "" {
			if _, err := os.Stat(s.ProjectPath); err != nil {
				continue
			}
		}
		filtered = append(filtered, s)
	}

	var activeStates map[string]scanner.ActiveState
	if cfg.ShowActive {
		activeStates = scanner.ActiveSessions()
	}

	m := tui.New(database, cfg, filtered, sessions, activeStates)
	p := tea.NewProgram(m, tea.WithAltScreen())
	if _, err := p.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func runDemo() {
	cfg := config.Config{
		ScanPaths:  []string{"~/Code"},
		SortBy:     "modified",
		ShowActive: true,
	}
	sessions := demo.Sessions()
	// Show both indicator states.
	activeStates := map[string]scanner.ActiveState{
		sessions[0].SessionID: scanner.StateBusy,
		sessions[1].SessionID: scanner.StateIdle,
	}
	m := tui.New(nil, cfg, sessions, nil, activeStates)
	p := tea.NewProgram(m, tea.WithAltScreen())
	if _, err := p.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}
