package demo

import (
	"time"

	"github.com/achton/cc360/internal/db"
)

// Sessions returns a set of realistic-looking fake sessions for demo/screenshot purposes.
func Sessions() []db.Session {
	now := time.Now()
	d := func(hours int) time.Time { return now.Add(-time.Duration(hours) * time.Hour) }

	return []db.Session{
		{
			SessionID:    "a1b2c3d4-1111-4000-8000-000000000001",
			ProjectName:  "Code/api-gateway",
			ProjectPath:  "/home/user/Code/api-gateway",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-api-gateway",
			Title:        "Rate limiter",
			FirstPrompt:  "Add rate limiting middleware to the API gateway",
			GitBranch:    "feat/rate-limit",
			MessageCount: 24,
			Created:      d(2),
			Modified:     d(1),
		},
		{
			SessionID:    "a1b2c3d4-2222-4000-8000-000000000002",
			ProjectName:  "Code/api-gateway",
			ProjectPath:  "/home/user/Code/api-gateway",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-api-gateway",
			Title:        "Auth middleware",
			FirstPrompt:  "The auth logic is duplicated across handlers, can you extract it?",
			GitBranch:    "main",
			MessageCount: 18,
			Created:      d(26),
			Modified:     d(24),
		},
		{
			SessionID:    "a1b2c3d4-3333-4000-8000-000000000003",
			ProjectName:  "Code/frontend",
			ProjectPath:  "/home/user/Code/frontend",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-frontend",
			Title:        "Dashboard redesign",
			FirstPrompt:  "Help me rebuild the dashboard using our new component library",
			GitBranch:    "redesign/dashboard",
			MessageCount: 42,
			Created:      d(4),
			Modified:     d(3),
		},
		{
			SessionID:    "a1b2c3d4-4444-4000-8000-000000000004",
			ProjectName:  "Code/frontend",
			ProjectPath:  "/home/user/Code/frontend",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-frontend",
			Title:        "Fix dark mode",
			FirstPrompt:  "Dark mode is broken when you nest theme providers",
			GitBranch:    "fix/dark-mode",
			MessageCount: 11,
			Created:      d(72),
			Modified:     d(70),
		},
		{
			SessionID:    "a1b2c3d4-5555-4000-8000-000000000005",
			ProjectName:  "Code/infra",
			ProjectPath:  "/home/user/Code/infra",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-infra",
			Title:        "Terraform modules",
			FirstPrompt:  "Our terraform is one giant main.tf, help me modularize it",
			GitBranch:    "refactor/modules",
			MessageCount: 31,
			Created:      d(50),
			Modified:     d(48),
		},
		{
			SessionID:    "a1b2c3d4-6666-4000-8000-000000000006",
			ProjectName:  "Code/docs-site",
			ProjectPath:  "/home/user/Code/docs-site",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-docs-site",
			Title:        "Search feature",
			FirstPrompt:  "I want to add search to the docs site using Pagefind",
			GitBranch:    "feat/search",
			MessageCount: 16,
			Created:      d(96),
			Modified:     d(90),
		},
		{
			SessionID:    "a1b2c3d4-7777-4000-8000-000000000007",
			ProjectName:  "Code/cli-tool",
			ProjectPath:  "/home/user/Code/cli-tool",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-cli-tool",
			Title:        "Config validation",
			FirstPrompt:  "We need to validate the config file on load and give useful errors",
			GitBranch:    "main",
			MessageCount: 9,
			Created:      d(120),
			Modified:     d(118),
		},
		{
			SessionID:    "a1b2c3d4-8888-4000-8000-000000000008",
			ProjectName:  "Code/ml-pipeline",
			ProjectPath:  "/home/user/Code/ml-pipeline",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-ml-pipeline",
			Title:        "Batch processing",
			FirstPrompt:  "The inference pipeline processes items sequentially, make it parallel",
			GitBranch:    "feat/batch",
			MessageCount: 27,
			Created:      d(144),
			Modified:     d(140),
		},
		{
			SessionID:    "a1b2c3d4-9999-4000-8000-000000000009",
			ProjectName:  "Code/mobile-app",
			ProjectPath:  "/home/user/Code/mobile-app",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-mobile-app",
			Title:        "Push notifications",
			FirstPrompt:  "We need push notifications that deep link to specific screens",
			GitBranch:    "feat/push",
			MessageCount: 35,
			Created:      d(168),
			Modified:     d(160),
		},
		{
			SessionID:    "a1b2c3d4-aaaa-4000-8000-000000000010",
			ProjectName:  "Code/api-gateway",
			ProjectPath:  "/home/user/Code/api-gateway",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-api-gateway",
			Title:        "OpenAPI spec",
			FirstPrompt:  "Can you generate an OpenAPI spec from our route handlers?",
			GitBranch:    "docs/openapi",
			MessageCount: 14,
			Created:      d(192),
			Modified:     d(190),
		},
		{
			SessionID:    "a1b2c3d4-bbbb-4000-8000-000000000011",
			ProjectName:  "Code/shared-libs/auth",
			ProjectPath:  "/home/user/Code/shared-libs/auth",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-shared-libs-auth",
			Title:        "OIDC provider",
			FirstPrompt:  "Implement OIDC support so we can use external identity providers",
			GitBranch:    "feat/oidc",
			MessageCount: 22,
			Created:      d(200),
			Modified:     d(196),
		},
		{
			SessionID:    "a1b2c3d4-cccc-4000-8000-000000000012",
			ProjectName:  "Code/frontend",
			ProjectPath:  "/home/user/Code/frontend",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-frontend",
			Title:        "Table component",
			FirstPrompt:  "We need a reusable table component that handles large datasets",
			GitBranch:    "feat/table",
			MessageCount: 19,
			Created:      d(220),
			Modified:     d(216),
		},
		{
			SessionID:    "a1b2c3d4-dddd-4000-8000-000000000013",
			ProjectName:  "Code/infra",
			ProjectPath:  "/home/user/Code/infra",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-infra",
			Title:        "CI pipeline",
			FirstPrompt:  "Help me set up CI with Go build matrix and dependency caching",
			GitBranch:    "ci/github-actions",
			MessageCount: 13,
			Created:      d(240),
			Modified:     d(238),
		},
		{
			SessionID:    "a1b2c3d4-eeee-4000-8000-000000000014",
			ProjectName:  "Code/cli-tool",
			ProjectPath:  "/home/user/Code/cli-tool",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-cli-tool",
			Title:        "Shell completions",
			FirstPrompt:  "Add shell completion support for all subcommands",
			GitBranch:    "feat/completions",
			MessageCount: 8,
			Created:      d(260),
			Modified:     d(258),
		},
		{
			SessionID:    "a1b2c3d4-ffff-4000-8000-000000000015",
			ProjectName:  "Code/docs-site",
			ProjectPath:  "/home/user/Code/docs-site",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-docs-site",
			Title:        "Migration guide",
			FirstPrompt:  "We need a migration guide for the v3 breaking changes",
			GitBranch:    "docs/v3-migration",
			MessageCount: 12,
			Created:      d(300),
			Modified:     d(296),
		},
		{
			SessionID:    "a1b2c3d4-1234-4000-8000-000000000016",
			ProjectName:  "Code/mobile-app",
			ProjectPath:  "/home/user/Code/mobile-app",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-mobile-app",
			Title:        "Offline mode",
			FirstPrompt:  "The app should work offline and sync when connectivity returns",
			GitBranch:    "feat/offline",
			MessageCount: 38,
			Created:      d(340),
			Modified:     d(330),
		},
		{
			SessionID:    "a1b2c3d4-5678-4000-8000-000000000017",
			ProjectName:  "Code/ml-pipeline",
			ProjectPath:  "/home/user/Code/ml-pipeline",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-ml-pipeline",
			Title:        "Model registry",
			FirstPrompt:  "We need a way to version and track our trained models",
			GitBranch:    "feat/registry",
			MessageCount: 20,
			Created:      d(380),
			Modified:     d(370),
		},
		{
			SessionID:    "a1b2c3d4-abcd-4000-8000-000000000018",
			ProjectName:  "Code/shared-libs/logging",
			ProjectPath:  "/home/user/Code/shared-libs/logging",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-shared-libs-logging",
			Title:        "Structured logging",
			FirstPrompt:  "Migrate all logging to Go's slog package with JSON output",
			GitBranch:    "refactor/slog",
			MessageCount: 15,
			Created:      d(400),
			Modified:     d(395),
		},
		// Worktree sessions
		{
			SessionID:    "a1b2c3d4-wt01-4000-8000-000000000019",
			ProjectName:  "Code/api-gateway/.claude/worktrees/pr-847",
			ProjectPath:  "/home/user/Code/api-gateway/.claude/worktrees/pr-847",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-api-gateway",
			Title:        "Fix CORS headers",
			FirstPrompt:  "Review this PR that changes CORS headers on the gateway",
			GitBranch:    "fix/cors-headers",
			MessageCount: 7,
			Created:      d(6),
			Modified:     d(5),
		},
		{
			SessionID:    "a1b2c3d4-wt02-4000-8000-000000000020",
			ProjectName:  "Code/frontend/.claude/worktrees/design-tokens",
			ProjectPath:  "/home/user/Code/frontend/.claude/worktrees/design-tokens",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-frontend",
			Title:        "Design tokens",
			FirstPrompt:  "Help me extract all the hardcoded color values into design tokens",
			GitBranch:    "feat/design-tokens",
			MessageCount: 15,
			Created:      d(10),
			Modified:     d(8),
		},
		{
			SessionID:    "a1b2c3d4-wt03-4000-8000-000000000021",
			ProjectName:  "Code/infra/.claude/worktrees/k8s-migration",
			ProjectPath:  "/home/user/Code/infra/.claude/worktrees/k8s-migration",
			ClaudeDir:    "~/.claude/projects/-home-user-Code-infra",
			Title:        "K8s migration",
			FirstPrompt:  "Convert our docker-compose setup to Kubernetes deployments",
			GitBranch:    "feat/k8s",
			MessageCount: 29,
			Created:      d(36),
			Modified:     d(30),
		},
	}
}
